# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- main

pool:
  vmImage: 'windows-latest'


jobs:
  - job: build_application
    pool:
        vmImage: 'windows-latest'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: 'restore'
        projects: 'Michal.Mucha.Service1/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        projects: 'Michal.Mucha.Service1/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet test TestProject'
      inputs:
        command: 'test'
        projects: 'Michal.Mucha.Service1.Tests/Michal.Mucha.Service1.Tests.csproj'



#- script: dotnet test <test-project> --logger trx
#- task: PublishTestResults@2
#  condition: succeededOrFailed()
#  inputs:
#    testRunner: VSTest
#    testResultsFiles: '**/*.trx'