trigger:
- main

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

#this typically would go to some config_file.ps1
#delivered later as env. varaiables on agent
#not done such just for simplicity
variables:
  dockerHub: 'docker_hub'
  dockerId: 'michalmuchadocker'


jobs:
  - job: service1
    displayName: Michal.Mucha.Service1
    steps:
    - template: /pipelines/azure-pipelines.yml
      parameters:
        serviceName: Michal.Mucha.Service1

  - job: service2
    displayName: Michal.Mucha.Service2
    dependsOn: service1
    steps:
    - template: /pipelines/azure-pipelines.yml
      parameters:
        serviceName: Michal.Mucha.Service2

  - job: service3
    displayName: Michal.Mucha.Service3
    dependsOn: service2
    steps:
    - template: /pipelines/azure-pipelines.yml
      parameters:
        serviceName: Michal.Mucha.Service3